### PR TITLE
Update README.md with more community information

### PR DESCRIPTION
**Pull request by jbeorse**

### CODE REVIEW

**Comment by jbeorse** [comment]
This is a suggestion of what our new READMEs might look like. After we settle on what we want I can propagate those changes to the rest of the projects.

**Comment by mitchellsundt** [comment]
Looks fine!

**Comment by jbeorse** [comment]
Umm, not sure how this got closed. Reopening so I can merge.

**Comment by jbeorse** [comment]
Whoops, the problem was that I accidentally force pushed over the top of my changes. I've recovered them from github's reflog and will open a new pull request and link to the discussion in this pull request.

**Pull request closed without merging**
