### PR TITLE
Replace hardcoded column name strings

### PR DESCRIPTION
**Pull request by akshay-ap**

### CODE REVIEW

**Comment by linl33** [comment]
runtests

**Comment by wbrunette** [comment]
There are still some hardcoded strings in androidlibrary_lib/src/main/java/org/opendatakit/utilities/NameUtil.java:69:

**Comment by jbeorse** [comment]
Agree with @wbrunette that there is more to be done, but it seems ok to me to merge this now and update the issue. Some progress is better than none. Thoughts @wbrunette and @linl33?

**Comment by linl33** [comment]
I'm fine with merging this first.

**Comment by wbrunette** [comment]
I am also fine with merging, but we should not close the issue.

**Pull request merged**
